### ISSUE TITLE
Config files have strict schema

### ISSUE THREAD

**Issue by RangerWhisky** [mcr-workex-17/build-checker#2]
The config files have a very strict schema - certain lines are used for specific values, with a comment above explaining what they do.

Using JSON or YAML is a much cleaner and more descriptive way to store configuration, allowing the python script to get parameters in a cleaner manner

**Comment by mcr-workex-17** [comment]
This has been changed. Now, the program uses JSON to load the required data from the config files. The config files store variables in dictionary form.

[Botson.zip](https://github.com/mcr-workex-17/build-checker/files/1138244/Botson.zip)
