### ISSUE TITLE
Implementation is dependent on Apache Jenkins instance

### ISSUE THREAD

**Issue by RangerWhisky** [mcr-workex-17/build-checker#4]
The script is very dependent on the specific interface form Apache Jenkins running on the web.

If this was split into two scripts, greater flexibility could be achieved.  One script could receive stimulus from Apache Jenkins, and then call to the slack script to publicise the results.  Results would passed as command line parameters, and interpreted using ArgParse in the slack publishing script

**Comment by mcr-workex-17** [comment]
none of us could figure out how to use ArgParse so we had to try a different way

**Comment by mcr-workex-17** [comment]
we also tried to use the jenkins api to get the data but that needed authorising before anything could be done

**Comment by RangerWhisky** [comment]
Resolved by splitting the scripts into GetData.py and SendToSlack.py
